name: ldm-test
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - altair==4.2.2
      - antlr4-python3-runtime==4.8
      - async-timeout==4.0.2
      - attrs==22.2.0
      - backports-zoneinfo==0.2.1
      - blinker==1.5
      - cachetools==5.3.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - colorama==0.4.6
      - decorator==5.1.1
      - diffusers==0.14.0
      - einops==0.6.0
      - entrypoints==0.4
      - filelock==3.9.0
      - frozenlist==1.3.3
      - fsspec==2023.3.0
      - ftfy==6.1.1
      - future==0.18.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - google-auth==2.16.2
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.3
      - huggingface-hub==0.16.4
      - idna==3.4
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - imgaug==0.2.6
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - invisible-watermark
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - kornia==0.6.4
      - lazy-loader==0.1
      - markdown==3.4.1
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - mdurl==0.1.2
      - multidict==6.0.4
      - networkx==3.0
      - numpy==1.24.2
      - oauthlib==3.2.2
      - omegaconf==2.1.1
      - opencv-python==4.1.2.30
      - opencv-python-headless==4.7.0.72
      - packaging==23.0
      - pandas==1.5.3
      - pkgutil-resolve-name==1.3.10
      - protobuf==3.20.3
      - pudb==2019.2
      - pyarrow==11.0.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydeck==0.8.0
      - pydeprecate==0.3.1
      - pygments==2.14.0
      - pympler==1.0.1
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytorch-lightning==1.4.2
      - pytz==2022.7.1
      - pytz-deprecation-shim==0.1.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - rich==13.3.2
      - rsa==4.9
      - sacremoses==0.0.53
      - scikit-image==0.20.0
      - scipy==1.9.1
      - semver==2.13.0
      - smmap==5.0.0
      - streamlit==1.20.0
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - test-tube==0.7.5
      - tifffile==2023.2.28
      - tokenizers==0.12.1
      - toml==0.10.2
      - toolz==0.12.0
      - torch==1.13.1
      - torch-fidelity==0.3.0
      - torchmetrics==0.6.0
      - torchvision==0.14.1
      - tornado==6.2
      - tqdm==4.65.0
      - transformers==4.31.0
      - tzdata==2022.7
      - tzlocal==4.2
      - urllib3==1.26.15
      - urwid==2.1.2
      - validators==0.20.0
      - watchdog==2.3.1
      - wcwidth==0.2.6
      - werkzeug==2.2.3
      - yarl==1.8.2
      - zipp==3.15.0
      - matplotlib==3.7.5
      - scikit-learn==1.3.2
      - seaborn==0.13.2
      - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
      - -e git+https://github.com/openai/CLIP.git@main#egg=clip
      - -e ./stable-diffusion